if exist('OnePath') == 0
	if exist('C:/Users/nick/OneDrive/Matlab_Code/NDH_Tools','dir') == 7
		 OnePath = 'C:/Users/nick/OneDrive/';
	elseif exist('C:/Users/Nick/Google Drive/Matlab_Code/') == 7
		OnePath = 'C:/Users/Nick/Google Drive/';
	elseif exist('C:/Users/nickh/Google_Drive2/Matlab_Code/') == 7
		OnePath = 'C:/Users/nickh/Google_Drive2/';
	elseif exist('C:/Users/Nick/Google_Drive2/Matlab_Code/') == 7
		OnePath = 'C:/Users/Nick/Google_Drive2/';
	elseif exist('D:/Users/Nick/Google_Drive2/Matlab_Code/') == 7
		OnePath = 'D:/Users/Nick/Google_Drive2/';
	elseif exist('D:/Users/Nick/Google_Drive/Matlab_Code/') == 7
		OnePath = 'D:/Users/Nick/Google_Drive/';
	elseif exist('C:/Users/nickh/Google_Drive/Matlab_Code/') == 7
		OnePath = 'C:/Users/nickh/Google_Drive/';
	elseif exist('G:/My Drive/Matlab_Code/') == 7
		OnePath = 'G:/My Drive/';
	elseif exist('/users/nholschuh/Matlab_Code/') == 7
		OnePath = '/users/nholschuh/';
	elseif exist('/Users/Lionheart/OneDrive/Matlab_Code/NDH_Tools','dir') == 7
		OnePath = '/Users/Lionheart/OneDrive/Matlab_Code/NDH_Tools';
	elseif exist('/data/rd00/Users/holschuh/Matlab_Code/') == 7
		OnePath = '/data/rd00/Users/holschuh/';
	elseif exist('/mnt/NDH_data/Google_Drive2/Matlab_Code/') == 7
		OnePath = '/mnt/NDH_data/Google_Drive2/';
	else
		OnePath = [];
	end
end


p = [...
    %%% BEGIN ENTRIES %%%
     OnePath,'Matlab_Code/NDH_Tools/TideModels;', ...
     OnePath,'Matlab_Code/NDH_Tools/TideModels/cats;', ...
     OnePath,'Matlab_Code/NDH_Tools/TideModels/cats/TMD;', ...
     OnePath,'Matlab_Code/NDH_Tools/TideModels/cats/TMD/DATA;', ...
     OnePath,'Matlab_Code/NDH_Tools/TideModels/cats/TMD/FUNCTIONS;', ...
     OnePath,'Matlab_Code/NDH_Tools/TideModels/cats/TMD/LAT_LON;', ...
     OnePath,'Matlab_Code/NDH_Tools/TideModels/cats/TMD/OUT;', ...
     OnePath,'Matlab_Code/NDH_Tools/TideModels/t_tide;', ...
     OnePath,'Matlab_Code/Other_Repos;', ...
     OnePath,'Matlab_Code/Other_Repos/topotoolbox-master;', ...
     OnePath,'Matlab_Code/Other_Repos/topotoolbox-master/DEMdata;', ...
     OnePath,'Matlab_Code/Other_Repos/topotoolbox-master/demos;', ...
     OnePath,'Matlab_Code/Other_Repos/topotoolbox-master/help;', ...
     OnePath,'Matlab_Code/Other_Repos/topotoolbox-master/topoapp;', ...
     OnePath,'Matlab_Code/Other_Repos/topotoolbox-master/ttlem;', ...
     OnePath,'Matlab_Code/Other_Repos/topotoolbox-master/ttlem/Help;', ...
     OnePath,'Matlab_Code/Other_Repos/topotoolbox-master/ttlem/Help/Documents;', ...
     OnePath,'Matlab_Code/Other_Repos/topotoolbox-master/ttlem/Help/results;', ...
     OnePath,'Matlab_Code/Other_Repos/topotoolbox-master/ttlem/LateralDisplacement;', ...
     OnePath,'Matlab_Code/Other_Repos/topotoolbox-master/ttlem/results;', ...
     OnePath,'Matlab_Code/Other_Repos/topotoolbox-master/utilities;', ...
     OnePath,'Matlab_Code/NDH_Tools;', ...
     OnePath,'Matlab_Code/NDH_Tools/REMA_Rools/;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/Ice_Divides;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/Line_Data;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/groundinglines;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/groundinglines/ASAID_gl_ant;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/groundinglines/IceSAT_gl_ant;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/groundinglines/MODIS_gl_ant;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/groundinglines/NDH_Greenland_gl;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/groundinglines/NDH_Greenland_gl/gland_surface_outlines_lonlat;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/groundinglines/NDH_Greenland_gl/gland_surface_outlines_xy;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/groundinglines/measures_gl_ant;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/topographies;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/topographies/LoadableTopographies_Antarctica;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/topographies/LoadableTopographies_Antarctica/bedmap2_tiff;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/topographies/LoadableTopographies_Antarctica/bedmachine_antarctica;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/topographies/LoadableTopographies_Greenland;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/topographies/LoadableTopographies_Greenland/Worldview_GreenlandSurf;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/velocities;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/velocities/Antarctic_Velocities;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/velocities/Antarctic_Velocities/Mouginot_PhaseVelocity;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/velocities/Greenland_Velocities;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/velocities/2015_Composite;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/other_data;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/other_data/Antarctic_Data;', ...
     OnePath,'Matlab_Code/NDH_Tools/CommonData_Searches/other_data/Greenland_Data;', ...
     OnePath,'Matlab_Code/NDH_Tools/FD_Model;', ...
     OnePath,'Matlab_Code/NDH_Tools/FD_Model/FD_Images;', ...
     OnePath,'Matlab_Code/NDH_Tools/From_Chevron_Work;', ...
     OnePath,'Matlab_Code/NDH_Tools/From_Chevron_Work/Summer_2014;', ...
     OnePath,'Matlab_Code/NDH_Tools/From_Chevron_Work/Summer_2015;', ...
     OnePath,'Matlab_Code/NDH_Tools/From_Chevron_Work/Summer_2015/4d_Inversion_Package;', ...
     OnePath,'Matlab_Code/NDH_Tools/From_Chevron_Work/Summer_2015/Portable_QC_Tool;', ...
     OnePath,'Matlab_Code/NDH_Tools/Geophysical_Tools;', ...
     OnePath,'Matlab_Code/NDH_Tools/Glaciology_Tools;', ...
     OnePath,'Matlab_Code/NDH_Tools/Graphical_Selection_Tools;', ...
     OnePath,'Matlab_Code/NDH_Tools/Matlab_GitArchive;', ...
     OnePath,'Matlab_Code/NDH_Tools/Matlab_GitArchive/.git;', ...
     OnePath,'Matlab_Code/NDH_Tools/Matlab_GitArchive/.git/hooks;', ...
     OnePath,'Matlab_Code/NDH_Tools/Matlab_GitArchive/.git/info;', ...
     OnePath,'Matlab_Code/NDH_Tools/Matlab_GitArchive/.git/logs;', ...
     OnePath,'Matlab_Code/NDH_Tools/Matlab_GitArchive/.git/logs/refs;', ...
     OnePath,'Matlab_Code/NDH_Tools/Matlab_GitArchive/.git/logs/refs/heads;', ...
     OnePath,'Matlab_Code/NDH_Tools/Matlab_GitArchive/.git/objects;', ...
     OnePath,'Matlab_Code/NDH_Tools/Matlab_GitArchive/.git/objects/4e;', ...
     OnePath,'Matlab_Code/NDH_Tools/Matlab_GitArchive/.git/objects/94;', ...
     OnePath,'Matlab_Code/NDH_Tools/Matlab_GitArchive/.git/objects/bd;', ...
     OnePath,'Matlab_Code/NDH_Tools/Matlab_GitArchive/.git/objects/cd;', ...
     OnePath,'Matlab_Code/NDH_Tools/Matlab_GitArchive/.git/objects/info;', ...
     OnePath,'Matlab_Code/NDH_Tools/Matlab_GitArchive/.git/objects/pack;', ...
     OnePath,'Matlab_Code/NDH_Tools/Matlab_GitArchive/.git/refs;', ...
     OnePath,'Matlab_Code/NDH_Tools/Matlab_GitArchive/.git/refs/heads;', ...
     OnePath,'Matlab_Code/NDH_Tools/Matlab_GitArchive/.git/refs/tags;', ...
     OnePath,'Matlab_Code/NDH_Tools/file_readers;', ...
     OnePath,'Matlab_Code/NDH_Tools/Music_Analysis;', ...
     OnePath,'Matlab_Code/NDH_Tools/Music_Analysis/Midi_Code;', ...
     OnePath,'Matlab_Code/NDH_Tools/Music_Analysis/mp3_toolbox;', ...
     OnePath,'Matlab_Code/NDH_Tools/Music_Analysis/mp3_toolbox/html;', ...
     OnePath,'Matlab_Code/NDH_Tools/NDH_CReSIS_Tools;', ...
     OnePath,'Matlab_Code/NDH_Tools/NetCDF_Manipulation;', ...
     OnePath,'Matlab_Code/NDH_Tools/colormaps;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/FOCI;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/Qtools;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/VSPtools;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/displaytools;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/editlines;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/fdElastic;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/finitedif;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/gabor_decon;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/icons;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/interpolation;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/interpolation/FGFT;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/inversion;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/migration;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/prertmtti;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/prertmtti/demo;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/prertmtti/src;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/raytrace;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/reflectivity;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/resolution;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/rockModel;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/seg2;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/segd;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/segy;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/segy/SEGY_Toolbox;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/seismic;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/startup_files;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/synsections;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/syntraces;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/utilities;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/velocity;', ...
     OnePath,'Matlab_Code/NDH_Tools/crewes/well_tying;', ...
     OnePath,'Matlab_Code/NDH_Tools/statistics_tests;', ...
     OnePath,'Matlab_Code/NDH_Tools/tarice_matlab_tools;', ...
     OnePath,'Matlab_Code/NDH_Tools/NDH_IceSat2_Tools;', ...
     OnePath,'Matlab_Code/storadar;', ...
     OnePath,'Matlab_Code/storadar/bin;', ...
     OnePath,'Matlab_Code/storadar/StoDeep;', ...
     OnePath,'Matlab_Code/storadar/StoDeep/Sample Data;', ...
     OnePath,'Matlab_Code/storadar/StoDeep/stodar_scripts;', ...
     OnePath,'Matlab_Code/storadar/StoDeep/stodar_scripts/Gui Moviedar;', ...
     OnePath,'Matlab_Code/storadar/StoDeep/stodar_scripts/utilities;', ...
     OnePath,'Matlab_Code/storadar/StoDeep/StoDeep_v2008b;', ...
     OnePath,'Matlab_Code/storadar/StoDeep/StoDeep_v2008b/StoDeepProcessing;', ...
     OnePath,'Matlab_Code/storadar/StoDeep/StoDeep_v2008b/StodeepRawLoad;', ...
     OnePath,'Matlab_Code/storadar/StoDeep/StoDeep_v2008b/StodeepRawLoad/USGS_radar;', ...
     OnePath,'Matlab_Code/storadar/StoDeep/StoGPS;', ...
     OnePath,'Matlab_Code/storadar/StoDeep/StoGPS/Garmin_GPS;', ...
     OnePath,'Matlab_Code/storadar/StoInterpret;', ...
     OnePath,'Matlab_Code/storadar/StoInterpret/user_files;', ...
     OnePath,'Matlab_Code/Other_Repos/SeisLab/S4M/Geophysics_3.0;', ...
    CresisPath,'OperationScripts;', ...
    CresisPath,'cresis-toolbox;', ...
    CresisPath,'cresis-toolbox/.git;', ...
    CresisPath,'cresis-toolbox/.git/branches;', ...
    CresisPath,'cresis-toolbox/.git/hooks;', ...
    CresisPath,'cresis-toolbox/.git/info;', ...
    CresisPath,'cresis-toolbox/.git/logs;', ...
    CresisPath,'cresis-toolbox/.git/logs/refs;', ...
    CresisPath,'cresis-toolbox/.git/logs/refs/heads;', ...
    CresisPath,'cresis-toolbox/.git/logs/refs/remotes;', ...
    CresisPath,'cresis-toolbox/.git/logs/refs/remotes/origin;', ...
    CresisPath,'cresis-toolbox/.git/objects;', ...
    CresisPath,'cresis-toolbox/.git/objects/info;', ...
    CresisPath,'cresis-toolbox/.git/objects/pack;', ...
    CresisPath,'cresis-toolbox/.git/refs;', ...
    CresisPath,'cresis-toolbox/.git/refs/heads;', ...
    CresisPath,'cresis-toolbox/.git/refs/remotes;', ...
    CresisPath,'cresis-toolbox/.git/refs/remotes/origin;', ...
    CresisPath,'cresis-toolbox/.git/refs/tags;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox-torque;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/accum;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/accum2;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/acords;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/acords/missions;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/cluster;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/ct_support;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/database;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/database/conversion;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/database/input;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/database/output;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/database/utility;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/deprecated;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/display;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/em_model;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/fmcw;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/gis;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/gps;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/gps/missions;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/gui;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/gui/table;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/hardware;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/hardware/sbox;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/icards;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/ice_crandall;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/json_mex;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/legacy;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/lidar;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/mcords;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/mcords2;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/mcords4;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/mcords5;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/mcrds;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/mcrds/missions;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/missions;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/OPS-MATLAB;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/OPS-MATLAB/conversion;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/OPS-MATLAB/conversion/jsonlab;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/OPS-MATLAB/conversion/jsonlab/examples;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/OPS-MATLAB/conversion/matlab-json;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/OPS-MATLAB/input;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/OPS-MATLAB/output;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/OPS-MATLAB/utility;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/parallel_proc;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/picker;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/posting;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/processing;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/rss;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/simulator;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/tidsor;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/utility;', ...
    CresisPath,'cresis-toolbox/cresis-toolbox/wise;', ...
    ];

addpath(p)



if ~verLessThan('matlab','9.5')
    set(groot,'defaultFigureCreateFcn',@(fig,~)addToolbarExplorationButtons(fig));
    set(groot,'defaultAxesCreateFcn',  @(ax,~)set(ax.Toolbar,'Visible','on'));
end


clearvars p

try
Projects
clear LastDir
end
clc


